// Mocks generated by Mockito 5.2.0 from annotations
// in my_doc_app_for_patients/test/features/auth/presentation/logic/auth_bloc/auth_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_doc_app_for_patients/core/errors/app_failures.dart' as _i5;
import 'package:my_doc_app_for_patients/core/usecase/base_usecase.dart' as _i6;
import 'package:my_doc_app_for_patients/features/auth/domain/usecases/email_and_password_params.dart'
    as _i9;
import 'package:my_doc_app_for_patients/features/auth/domain/usecases/register_with_email_and_password.dart'
    as _i8;
import 'package:my_doc_app_for_patients/features/auth/domain/usecases/register_with_facebook_usecase.dart'
    as _i3;
import 'package:my_doc_app_for_patients/features/auth/domain/usecases/register_with_google_usecase.dart'
    as _i7;
import 'package:my_doc_app_for_patients/features/auth/domain/usecases/sign_in_with_email_and_password_usecase.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [RegisterWithFacebookUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterWithFacebookUsecase extends _i1.Mock
    implements _i3.RegisterWithFacebookUsecase {
  MockRegisterWithFacebookUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailures, _i2.Unit>> call(
          _i6.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i2.Either<_i5.AuthFailures, _i2.Unit>>.value(
                  _FakeEither_0<_i5.AuthFailures, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.AuthFailures, _i2.Unit>>);
}

/// A class which mocks [RegisterWithGoogleUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterWithGoogleUsecase extends _i1.Mock
    implements _i7.RegisterWithGoogleUsecase {
  MockRegisterWithGoogleUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailures, _i2.Unit>> call(
          _i6.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i2.Either<_i5.AuthFailures, _i2.Unit>>.value(
                  _FakeEither_0<_i5.AuthFailures, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.AuthFailures, _i2.Unit>>);
}

/// A class which mocks [RegisterWithEmailAndPasswordUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterWithEmailAndPasswordUsecase extends _i1.Mock
    implements _i8.RegisterWithEmailAndPasswordUsecase {
  MockRegisterWithEmailAndPasswordUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailures, _i2.Unit>> call(
          _i9.EmailAndPasswordParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i2.Either<_i5.AuthFailures, _i2.Unit>>.value(
                  _FakeEither_0<_i5.AuthFailures, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.AuthFailures, _i2.Unit>>);
}

/// A class which mocks [SignInWithEmailAndPasswordUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithEmailAndPasswordUsecase extends _i1.Mock
    implements _i10.SignInWithEmailAndPasswordUsecase {
  MockSignInWithEmailAndPasswordUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailures, _i2.Unit>> call(
          _i9.EmailAndPasswordParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i2.Either<_i5.AuthFailures, _i2.Unit>>.value(
                  _FakeEither_0<_i5.AuthFailures, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.AuthFailures, _i2.Unit>>);
}
